name: Release app
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: 'windows-latest'
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v2.0.0
        with:
          node_version: 20
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn run publish
